### ISSUE TITLE
Change summary for duo_bypass_codes_used

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef-Triage-Bot#4]
I'm unsure where to file this so I'll do so here and we can move it if need be

The Summary field for `duo_bypass_codes_used` events appears to be

`DUO bypass codes belonging to your account have been used to `

Is this a prefix to a string and something gets appended or is it missing the remainder of the string? What would this look like when it's sent to the triage bot?

**Comment by arcrose** [comment]
This appears to have been due to a syntax mistake that didn't amount to an error.  I've fixed it in [commit](https://github.com/mozilla/MozDef/commit/d521f5ece45d6f2bffa01520edbcdb68ae4c7228) just now.  When everything's updated, you should get the full summary messages modified here.
