### ISSUE TITLE
"user" field contents question

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef-Triage-Bot#8]
For the `user` field of the [alert triage request](https://github.com/mozilla/MozDef-Triage-Bot/blob/master/docs/specifications/v0_1.md#alert-triage-requests), the docs say the field will contain an email address.

For alerts like the ssh based alerts, will the alert action resolve the posix username to an email address? If so can you link to the code that does this, I wasn't able to find it.

**Comment by arcrose** [comment]
Sure thing. There is one function for each alert we support right now at the bottom of the [alert action](https://github.com/mozilla/MozDef/blob/feature-triage-bot/alerts/actions/triage_bot.py#L463) code.  You'll see that, in the cases of duo alerts we already have the email address so we don't reach out to the person API.  In other cases, we do query the person API and make an "informed" guess as a fallback.

**Comment by gene1wood** [comment]
Excellent. It will always be an email address, it just might not always be correct. And I see this [fallback code](https://github.com/mozilla/MozDef/blob/64fcd277840e28049c8d256612309fef5d8926ad/alerts/actions/triage_bot.py#L471) as well. Great, thank you.
